---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: stress
spec:
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: stress
  minReplicas: 1
  maxReplicas: 180
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 15