dist: xenial
language: minimal

before_install:
  - sudo apt-get -y update
  - sudo apt-get -y install zip make wget python
  - sudo apt-get -y install python-pip
  - sudo pip install awscli
  - sudo sh docs/install/terraform.sh
  - sudo sh docs/install/kubectl.sh
  - sudo sh docs/install/helm.sh

install:
  - travis_wait 60 make quickstart