apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: $NAME
  region: $AWS_REGION
<<<<<<< HEAD

vpc:
  subnets:
    private:
      b: { id: a }
      b: { id: a }
      b: { id: a }
    public:
      b: { id: a }
      b: { id: a }
      b: { id: a }

nodeGroups:
  - name: $NAME
    minSize: 0
    maxSize: 10
    volumeSize: 60
    privateNetworking: true
    ssh:
      allow: true
    instancesDistribution:
      instanceTypes: ["r5a.large", "m5a.large"]
=======
  version: "$KUBE_VER"

nodeGroups:
  - name: $NAME
    minSize: $NODE_MIN
    maxSize: $NODE_MAX
    desiredCapacity: 1
    volumeSize: 60
    privateNetworking: true
    instancesDistribution:
      instanceTypes: $NODE_TYPE
>>>>>>> 1a914d3 (varios cambios)
      onDemandPercentageAboveBaseCapacity: 25
    iam:
      withAddonPolicies:
        autoScaler: true
<<<<<<< HEAD
=======
        cloudWatch: true
        ebs: true

availabilityZones: $AWS_ZONES
>>>>>>> 1a914d3 (varios cambios)

cloudWatch:
  clusterLogging:
    enableTypes: ["audit", "authenticator", "controllerManager"]