alertmanager:
  enabled: false

nodeExporter:
  enabled: true

server:
  enabled: true
  persistentVolume:
    enabled: false
    size: 8Gi
    storageClass: "gp2"
  env:
  - name: JAEGER_AGENT_PORT
    value: "6831"

pushgateway:
  enabled: false

extraScrapeConfigs: |
  - job_name: 'traefik'
    metrics_path: /metrics
    static_configs:
      - targets:
        - traefik-metrics.default.svc.cluster.local:8082