image:
  name: traefik
  tag: 2.3.1
  pullPolicy: IfNotPresent

service:
  enabled: true
  type: LoadBalancer
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 4
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 95

logs:
  general:
    level: ERROR
  access:
    enabled: true

additionalArguments:
  - "--tracing.jaeger.localagenthostport=jaeger-agent.default.svc.cluster.local:6831"
  - "--metrics.prometheus.addEntryPointsLabels=true"
  - "--metrics.prometheus.addServicesLabels=true"
  - "--metrics.prometheus=true"
  - "--metrics.prometheus.entryPoint=metrics"
  - "--entryPoints.metrics.address=:8082"